# Generated by Django 5.0 on 2024-01-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('idFasilitas', models.AutoField(primary_key=True, serialize=False)),
                ('namaFasilitas', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('idPetugas', models.AutoField(primary_key=True, serialize=False)),
                ('namaPetugas', models.CharField(max_length=60)),
                ('jKelamin', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=1)),
                ('tanggalLahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('alamat', models.CharField(max_length=100)),
                ('noTlpn', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('level', models.CharField(choices=[('ADM', 'Admin'), ('PTG', 'Petugas')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('idRuangan', models.AutoField(primary_key=True, serialize=False)),
                ('namaRuangan', models.CharField(max_length=60)),
                ('luasRuangan', models.SmallIntegerField(default=0, verbose_name='Luas Ruangan')),
                ('kapasitasOrang', models.SmallIntegerField(default=0, verbose_name='Kapasitas Orang')),
                ('jTempatTidur', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], max_length=6)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('idReservasi', models.AutoField(primary_key=True, serialize=False)),
                ('namaPelanggan', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
                ('checkIn', models.DateField(verbose_name='Check In')),
                ('checkOut', models.DateField(verbose_name='Check Out')),
                ('waktuPesanan', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('idRuangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.ruangan')),
            ],
        ),
        migrations.CreateModel(
            name='RuanganFasilitas',
            fields=[
                ('idRF', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahBarang', models.SmallIntegerField(default=0, verbose_name='Jumlah Barang')),
                ('idFasilitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.fasilitas')),
                ('idRuangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.ruangan')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('idTransaksi', models.AutoField(primary_key=True, serialize=False)),
                ('kodeTransaksi', models.CharField(max_length=13)),
                ('tanggalTransaksi', models.DateTimeField()),
                ('nominal', models.IntegerField()),
                ('status', models.CharField(choices=[('PRS', 'Proses'), ('LNS', 'Lunas'), ('BTL', 'Batal')], max_length=10)),
                ('idReservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.reservasi')),
            ],
        ),
    ]
