# Generated by Django 4.2.9 on 2024-01-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0002_delete_petugas_alter_transaksi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
