# Generated by Django 4.2.9 on 2024-01-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0003_ruangan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='idRuangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.ruangan'),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='waktuPesanan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ruanganfasilitas',
            name='idFasilitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.fasilitas'),
        ),
        migrations.AlterField(
            model_name='ruanganfasilitas',
            name='idRuangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.ruangan'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='idReservasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.reservasi'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('Proses', 'proses'), ('Lunas', 'lunas'), ('Batal', 'batal')], max_length=10),
        ),
    ]
