# Generated by Django 4.2.9 on 2024-01-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0004_alter_reservasi_idruangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
