# Generated by Django 4.2.9 on 2024-01-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0005_alter_ruangan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
