# Generated by Django 4.2.9 on 2024-01-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasilitas', '0001_initial'),
        ('ruangan', '0006_alter_ruangan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruanganfasilitas',
            name='idFasilitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasilitas.fasilitas'),
        ),
        migrations.DeleteModel(
            name='Fasilitas',
        ),
    ]
