# Generated by Django 4.2.9 on 2024-01-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0007_alter_ruanganfasilitas_idfasilitas_delete_fasilitas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuanganFasilitas',
        ),
    ]
