# Generated by Django 4.2.9 on 2024-01-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0008_delete_ruanganfasilitas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
