# Generated by Django 4.2.9 on 2024-01-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0009_delete_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
