# Generated by Django 4.2.9 on 2024-01-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0010_alter_reservasi_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='status',
            field=models.CharField(choices=[('Belum Check In', 'Proses'), ('Sudah Check In', 'Check In'), ('Sudah Check Out', 'Check Out')], default='Belum Check In', max_length=20),
        ),
    ]
