# Generated by Django 4.2.9 on 2024-01-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('idPetugas', models.AutoField(primary_key=True, serialize=False)),
                ('namaPetugas', models.CharField(max_length=60)),
                ('jKelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('tanggalLahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('alamat', models.CharField(max_length=100)),
                ('noTlpn', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('level', models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas')], max_length=10)),
            ],
        ),
    ]
