# Generated by Django 4.2.9 on 2024-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petugas',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
