# Generated by Django 4.2.9 on 2024-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_petugas_last_login_alter_petugas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petugas',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
