# Generated by Django 4.2.9 on 2024-01-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruangan', '0009_delete_transaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('idTransaksi', models.AutoField(primary_key=True, serialize=False)),
                ('kodeTransaksi', models.CharField(max_length=13)),
                ('tanggalTransaksi', models.DateTimeField()),
                ('nominal', models.IntegerField()),
                ('status', models.CharField(choices=[('Proses', 'proses'), ('Lunas', 'lunas'), ('Batal', 'batal')], max_length=10)),
                ('idReservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.reservasi')),
            ],
        ),
    ]
