# Generated by Django 4.2.9 on 2024-01-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='nominal',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
