# Generated by Django 4.2.9 on 2024-01-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruangan', '0008_delete_ruanganfasilitas'),
        ('fasilitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuanganFasilitas',
            fields=[
                ('idRF', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahBarang', models.SmallIntegerField(default=0, verbose_name='Jumlah Barang')),
                ('idFasilitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasilitas.fasilitas')),
                ('idRuangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.ruangan')),
            ],
        ),
    ]
